branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- bash ci/build
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - GH_TOKEN=2600e84214fe6d3fdaf3174682dcb748497a4053
before_install:
  - git submodule update --init --recursive
after_success: bash ci/deploy.sh
